# Generated by Django 5.2.12 on 2026-03-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='volunteer_id',
            new_name='volunteer',
        ),
    ]
