# Generated by Django 5.2.12 on 2026-03-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
