class User {
  +id : int
  +username : str
  +first_name : str
  +last_name : str
  +email : str
  +password : str
}

class Competence {
  +id : int
  +nom : str
  +description : str
}

class Service {
  +id : int
  +activite : str
  +date_creneau : date
  +date_creation : datetime
  +pourvue : bool
}

User "1" -- "*" Service : crée >
Service "*" -- "1" Competence : requiert >
Service "*" -- "0..1" User : volontaire >
User "1" -- "*" Competence : possède >